---
abstract: 'Access Radio Thermostat Co of America (3M-Filtrete) WiFi thermostats'
author:
  - 'Mike Greb <michael@thegrebs.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-RadioThermostat
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  JSON: 2
  LWP::UserAgent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/mikegrb/Device-RadioThermostat/issues
  homepage: https://github.com/mikegrb/Device-RadioThermostat
  repository: https://github.com/mikegrb/Device-RadioThermostat.git
version: 0.03
x_contributors:
  - 'Philip Gladstone <philip@gladstonefamily.net>'
  - 'mikegrb <mgreb@linode.com>'
